### ISSUE TITLE
你好我只想要你的预训练模型的word embedding该如何操作呢

### ISSUE THREAD

**Issue by Yuanml1225** [txsun1997/CoLAKE#1]

**Comment by txsun1997** [comment]
我们放出了预训练的[model](https://drive.google.com/file/d/1MEGcmJUBXOyxKaK6K88fZFyj_IbH9U5b/view?usp=sharing)和[entity embedding](https://drive.google.com/file/d/1_FG9mpTrOnxV2NolXlu1n2ihgSZFXHnI/view?usp=sharing)，可以只下载其中的model

**Comment by Yuanml1225** [comment]
那后者用于什么呢？前者已经包含了知识图谱了吧？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Tianxiang Sun <notifications@github.com&gt;
发送时间: 2020年11月3日 22:25
收件人: txsun1997/CoLAKE <CoLAKE@noreply.github.com&gt;
抄送: Yuanml1225 <331872074@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[txsun1997/CoLAKE] 你好我只想要你的预训练模型的word embedding该如何操作呢 (#1)





 
我们放出了预训练的model和entity embedding，可以只下载其中的model

**Comment by txsun1997** [comment]
后者包含了约30万个entity的embedding，可以用于知识图谱上的一些任务以及entity linking等知识相关的任务。前者就是一个pretrained Transformer，但包含了relation embedding
