### ISSUE TITLE
Code Question

### ISSUE THREAD

**Issue by GX77** [txsun1997/CoLAKE#15]
您好，请问对于一个输入的句子，如何提取出句子中的实体？
论文中由于是输入的网页文档，可以直接根据“\<a>”来提取实体，但一般的句子并没有这样的标记，那这个Entity Linker如何设计呢？可以让句子中的每个词去和Entity库匹配吗

**Comment by txsun1997** [comment]
论文中有提到，用了一个第三方库TAGME去找出句子里的实体。另外我们发现就算不找出实体直接就用colake的参数去做关系抽取等下游任务提升也很明显
