### ISSUE TITLE
请教问题

### ISSUE THREAD

**Issue by leileilin** [txsun1997/CoLAKE#17]
你好，
非常感谢你们开源这么棒的工作！
你文中说输入句子中的实体会被链接实体给替换，但是论文的样例图显示的是没替换的，你能帮我解释一下是真的替换还是没有？
谢谢！

**Comment by txsun1997** [comment]
是真的替换，图中示例应该也是替换掉的（红边蓝底的圆圈），你指的样例图是哪张？
