### ISSUE TITLE
vocab 文件

### ISSUE THREAD

**Issue by wangchichi1999** [txsun1997/CoLAKE#9]
嗨！您好呀：
有一个问题，可不可以用CoLAKE的预训练模型model.bin直接替换之前pytorch代码里的英文bert模型呢？
如果可以的话，之前用pytorch的bert的时候通常需要model.bin和vocab.txt两个文件，vocab文件还是用之前的的咩？
（小白发言）

**Comment by txsun1997** [comment]
CoLAKE是基于RoBERTa，所以vocab文件和RoBERTa一样，不能替换BERT，可以替换RoBERTa

**Comment by wangchichi1999** [comment]
Thanks！！！！
跑起来了而且效果很不错！
